import { contextBridge, ipcRenderer, webUtils, type IpcRendererEvent } from 'electron'
import type { Api, Progress } from '../shared-types'

// 메인이 보내는 이벤트를 구독하고, 해제 함수를 돌려준다
function subscribe<T>(channel: string, fn: (data: T) => void): () => void {
  const listener = (_e: IpcRendererEvent, data: T) => fn(data)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

const api: Api = {
  getVersions: (includeSnapshots) => ipcRenderer.invoke('getVersions', includeSnapshots),
  getLoaderVersions: (software, mcVersion) => ipcRenderer.invoke('getLoaderVersions', software, mcVersion),
  createServer: (options, taskId) => ipcRenderer.invoke('createServer', options, taskId),
  onCreateProgress: (fn) => subscribe<{ taskId: string; progress: Progress }>('createProgress', (d) => fn(d.taskId, d.progress)),
  listServers: () => ipcRenderer.invoke('listServers'),
  openFolder: (folderPath) => ipcRenderer.invoke('openFolder', folderPath),
  deleteServer: (folderPath) => ipcRenderer.invoke('deleteServer', folderPath),
  cancelCreate: (taskId) => ipcRenderer.invoke('cancelCreate', taskId),
  browseModpacks: (o) => ipcRenderer.invoke('browseModpacks', o),
  gameVersions: () => ipcRenderer.invoke('gameVersions'),
  prepareModpackFile: (file) => ipcRenderer.invoke('prepareModpackFile', webUtils.getPathForFile(file)),
  pickModpackFile: () => ipcRenderer.invoke('pickModpackFile'),
  modpackVersions: (projectId, source) => ipcRenderer.invoke('modpackVersions', projectId, source),
  prepareCurseForgeModpack: (modId, fileId) => ipcRenderer.invoke('prepareCurseForgeModpack', modId, fileId),
  prepareModpack: (versionId) => ipcRenderer.invoke('prepareModpack', versionId),
  setServerOrder: (folderPaths) => ipcRenderer.invoke('setServerOrder', folderPaths),
  renameServer: (folderPath, name) => ipcRenderer.invoke('renameServer', folderPath, name),
  duplicateServer: (folderPath, name) => ipcRenderer.invoke('duplicateServer', folderPath, name),
  windowControl: (action) => ipcRenderer.invoke('windowControl', action),
  isMaximized: () => ipcRenderer.invoke('isMaximized'),
  onWindowMaximized: (fn) => subscribe('windowMaximized', fn),
  onConfirmQuit: (fn) => subscribe('confirmQuit', fn),
  quitApp: () => ipcRenderer.invoke('quitApp'),
  getUpdate: () => ipcRenderer.invoke('getUpdate'),
  onUpdate: (fn) => subscribe('update', fn),
  installUpdate: () => ipcRenderer.invoke('installUpdate'),
  getSiteStatus: () => ipcRenderer.invoke('getSiteStatus'),
  onSiteStatus: (fn) => subscribe('siteStatus', fn),
  onBugReplies: (fn) => subscribe('bugReplies', fn),
  getMyBugReports: () => ipcRenderer.invoke('getMyBugReports'),
  markBugRepliesSeen: () => ipcRenderer.invoke('markBugRepliesSeen'),
  refreshBugReplies: () => ipcRenderer.invoke('refreshBugReplies'),
  getInbox: () => ipcRenderer.invoke('getInbox'),
  preflight: (folderPath) => ipcRenderer.invoke('preflight', folderPath),
  openEulaPage: () => ipcRenderer.invoke('openEulaPage'),
  acceptEula: (folderPath) => ipcRenderer.invoke('acceptEula', folderPath),
  startServer: (folderPath) => ipcRenderer.invoke('startServer', folderPath),
  stopServer: (folderPath, force) => ipcRenderer.invoke('stopServer', folderPath, force),
  sendCommand: (folderPath, command) => ipcRenderer.invoke('sendCommand', folderPath, command),
  getLog: (folderPath) => ipcRenderer.invoke('getLog', folderPath),
  getInvite: (folderPath) => ipcRenderer.invoke('getInvite', folderPath),
  checkReachable: (folderPath) => ipcRenderer.invoke('checkReachable', folderPath),
  useTunnel: (folderPath) => ipcRenderer.invoke('useTunnel', folderPath),
  getStats: (folderPath) => ipcRenderer.invoke('getStats', folderPath),
  getManageInfo: (folderPath) => ipcRenderer.invoke('getManageInfo', folderPath),
  getPlayerHistory: (folderPath) => ipcRenderer.invoke('getPlayerHistory', folderPath),
  manage: (folderPath, action) => ipcRenderer.invoke('manage', folderPath, action),
  listGameRules: (folderPath) => ipcRenderer.invoke('listGameRules', folderPath),
  setGameRule: (folderPath, name, value) => ipcRenderer.invoke('setGameRule', folderPath, name, value),
  getGameRuleLang: (folderPath) => ipcRenderer.invoke('getGameRuleLang', folderPath),
  getSettings: (folderPath) => ipcRenderer.invoke('getSettings', folderPath),
  saveSettings: (folderPath, settings) => ipcRenderer.invoke('saveSettings', folderPath, settings),
  resetWorld: (folderPath) => ipcRenderer.invoke('resetWorld', folderPath),
  changeVersion: (folderPath, mcVersion, loaderVersion) => ipcRenderer.invoke('changeVersion', folderPath, mcVersion, loaderVersion),
  onVersionProgress: (fn) => subscribe<Progress>('versionProgress', fn),
  listBackups: (folderPath) => ipcRenderer.invoke('listBackups', folderPath),
  createBackup: (folderPath) => ipcRenderer.invoke('createBackup', folderPath),
  restoreBackup: (folderPath, id) => ipcRenderer.invoke('restoreBackup', folderPath, id),
  deleteBackup: (folderPath, id) => ipcRenderer.invoke('deleteBackup', folderPath, id),
  openBackupFolder: (folderPath) => ipcRenderer.invoke('openBackupFolder', folderPath),
  getBackupSettings: (folderPath) => ipcRenderer.invoke('getBackupSettings', folderPath),
  getServerIcon: (folderPath) => ipcRenderer.invoke('getServerIcon', folderPath),
  pickServerIcon: (folderPath) => ipcRenderer.invoke('pickServerIcon', folderPath),
  pickIconImage: () => ipcRenderer.invoke('pickIconImage'),
  setServerIconFile: (folderPath, file) => ipcRenderer.invoke('setServerIconFile', folderPath, webUtils.getPathForFile(file)),
  removeServerIcon: (folderPath) => ipcRenderer.invoke('removeServerIcon', folderPath),
  setBackupSettings: (folderPath, s) => ipcRenderer.invoke('setBackupSettings', folderPath, s),
  listSaves: () => ipcRenderer.invoke('listSaves'),
  pickWorldZip: () => ipcRenderer.invoke('pickWorldZip'),
  // 끌어다 놓은 파일의 실제 경로 (sandbox에서는 File.path가 없어서 webUtils로 얻는다)
  openDroppedWorld: (file) => ipcRenderer.invoke('openDroppedWorld', webUtils.getPathForFile(file)),
  openExternal: (url) => ipcRenderer.invoke('openExternal', url),
  sendBugReport: (title, details, files) => ipcRenderer.invoke('sendBugReport', title, details, files),
  pickBugFiles: () => ipcRenderer.invoke('pickBugFiles'),
  bugFileInfo: (file) => ipcRenderer.invoke('bugFileInfo', webUtils.getPathForFile(file)),
  openCrashReport: (folderPath, reportPath) => ipcRenderer.invoke('openCrashReport', folderPath, reportPath),
  disableDatapack: (folderPath, name) => ipcRenderer.invoke('disableDatapack', folderPath, name),
  installModById: (folderPath, modId) => ipcRenderer.invoke('installModById', folderPath, modId),
  hasCurseForgeKey: () => ipcRenderer.invoke('hasCurseForgeKey'),
  removeCurseForgeKey: () => ipcRenderer.invoke('removeCurseForgeKey'),
  getAppInfo: () => ipcRenderer.invoke('getAppInfo'),
  unlinkTunnel: () => ipcRenderer.invoke('unlinkTunnel'),
  setAppSettings: (patch) => ipcRenderer.invoke('setAppSettings', patch),
  openDataFolder: () => ipcRenderer.invoke('openDataFolder'),
  listDir: (folderPath, rel) => ipcRenderer.invoke('listDir', folderPath, rel),
  renameEntry: (folderPath, rel, newName) => ipcRenderer.invoke('renameEntry', folderPath, rel, newName),
  trashEntries: (folderPath, rels) => ipcRenderer.invoke('trashEntries', folderPath, rels),
  createEntry: (folderPath, rel, name, kind) => ipcRenderer.invoke('createEntry', folderPath, rel, name, kind),
  revealEntry: (folderPath, rel) => ipcRenderer.invoke('revealEntry', folderPath, rel),
  readConfigFile: (folderPath, rel) => ipcRenderer.invoke('readConfigFile', folderPath, rel),
  writeConfigFile: (folderPath, rel, text, expectedModified) => ipcRenderer.invoke('writeConfigFile', folderPath, rel, text, expectedModified),
  setCurseForgeKey: (key) => ipcRenderer.invoke('setCurseForgeKey', key),
  searchMaps: (query, sort, offset) => ipcRenderer.invoke('searchMaps', query, sort, offset),
  mapFiles: (modId) => ipcRenderer.invoke('mapFiles', modId),
  prepareMap: (modId, fileId, title) => ipcRenderer.invoke('prepareMap', modId, fileId, title),
  onMapProgress: (fn) => subscribe('mapProgress', fn),
  cancelMap: () => ipcRenderer.invoke('cancelMap'),
  importWorld: (folderPath, source) => ipcRenderer.invoke('importWorld', folderPath, source),
  getHardcore: (folderPath) => ipcRenderer.invoke('getHardcore', folderPath),
  setHardcore: (folderPath, on) => ipcRenderer.invoke('setHardcore', folderPath, on),
  getWhitelist: (folderPath) => ipcRenderer.invoke('getWhitelist', folderPath),
  setWhitelistEnabled: (folderPath, enabled) => ipcRenderer.invoke('setWhitelistEnabled', folderPath, enabled),
  addWhitelist: (folderPath, name) => ipcRenderer.invoke('addWhitelist', folderPath, name),
  removeWhitelist: (folderPath, name) => ipcRenderer.invoke('removeWhitelist', folderPath, name),
  modKind: (folderPath) => ipcRenderer.invoke('modKind', folderPath),
  searchMods: (folderPath, query, page, site) => ipcRenderer.invoke('searchMods', folderPath, query, page, site),
  installMod: (folderPath, projectId) => ipcRenderer.invoke('installMod', folderPath, projectId),
  listMods: (folderPath) => ipcRenderer.invoke('listMods', folderPath),
  removeMod: (folderPath, fileName) => ipcRenderer.invoke('removeMod', folderPath, fileName),
  offSuggestions: (folderPath) => ipcRenderer.invoke('offSuggestions', folderPath),
  applyOffSuggestions: (folderPath, fileNames) => ipcRenderer.invoke('applyOffSuggestions', folderPath, fileNames),
  identifyMods: (folderPath) => ipcRenderer.invoke('identifyMods', folderPath),
  exportClientPack: (folderPath, format) => ipcRenderer.invoke('exportClientPack', folderPath, format),
  addModFile: (folderPath, file) => ipcRenderer.invoke('addModFile', folderPath, webUtils.getPathForFile(file)),
  modVersions: (folderPath, fileName) => ipcRenderer.invoke('modVersions', folderPath, fileName),
  setModVersion: (folderPath, fileName, versionId) => ipcRenderer.invoke('setModVersion', folderPath, fileName, versionId),
  listDatapacks: (folderPath) => ipcRenderer.invoke('listDatapacks', folderPath),
  identifyDatapacks: (folderPath) => ipcRenderer.invoke('identifyDatapacks', folderPath),
  searchDatapacks: (folderPath, query, page, site) => ipcRenderer.invoke('searchDatapacks', folderPath, query, page, site),
  installDatapack: (folderPath, projectId) => ipcRenderer.invoke('installDatapack', folderPath, projectId),
  setDatapackEnabled: (folderPath, name, enabled) => ipcRenderer.invoke('setDatapackEnabled', folderPath, name, enabled),
  removeDatapack: (folderPath, name) => ipcRenderer.invoke('removeDatapack', folderPath, name),
  datapackVersions: (folderPath, name) => ipcRenderer.invoke('datapackVersions', folderPath, name),
  setDatapackVersion: (folderPath, name, versionId) => ipcRenderer.invoke('setDatapackVersion', folderPath, name, versionId),
  addDatapackFile: (folderPath, file) => ipcRenderer.invoke('addDatapackFile', folderPath, webUtils.getPathForFile(file)),
  checkModUpdates: (folderPath) => ipcRenderer.invoke('checkModUpdates', folderPath),
  updateMods: (folderPath, fileNames) => ipcRenderer.invoke('updateMods', folderPath, fileNames),
  setModEnabled: (folderPath, fileName, enabled) => ipcRenderer.invoke('setModEnabled', folderPath, fileName, enabled),
  copyText: (text) => ipcRenderer.invoke('copyText', text),
  onProgress: (fn) => subscribe('progress', fn),
  onServerEvent: (fn) => subscribe('serverEvent', fn)
}

contextBridge.exposeInMainWorld('api', api)
